### PR TITLE
Added Ruby client example

### PR DESCRIPTION
**Pull request by rojosinalma**
A simple port from the python client.

### CODE REVIEW

**Comment by rojosinalma** [comment]
ping @AnthorNet

**Comment by inorton** [comment]
I love that this thing has almost become a rosetta stone for different languages!

**Comment by rojosinalma** [comment]
Is there any maintainer checking PRs still?

**Comment by AnthorNet** [comment]
Yes, but there was also updates to deal with, crisis and such ;)

**Comment by rojosinalma** [comment]
Ah sorry if that came across as pushy, it was an honest question 😅 
Happens a lot in Github.

**Pull request merged**
